# Generated by Django 5.0.6 on 2024-06-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Free', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='free',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='book.freebook'),
            preserve_default=False,
        ),
    ]
