# Generated by Django 5.0.6 on 2024-06-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_freebook_book_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='free',
        ),
        migrations.DeleteModel(
            name='FreeBook',
        ),
    ]
